
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dp
  labels:
    app: myapp
spec:
  replicas: 4
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
       app: myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: regcrd
      containers:
      - name: myapp-container
        image: nadeempatel/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 800m
            memory: 1Gi
 
---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
